import io.gitlab.arturbosch.detekt.Detekt
import com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask
import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget
import java.net.URI

plugins {
    alias(libs.plugins.multiplatform)
    alias(libs.plugins.serialization)
    distribution
    alias(libs.plugins.dokka)
    alias(libs.plugins.aboutlibraries)
    alias(libs.plugins.buildconfig)

    alias(libs.plugins.gradle.versions)
    alias(libs.plugins.detekt)
}

group = "dev.sriniketh"
version = getVersionNameFromGitTags()

repositories {
    mavenCentral()
}

kotlin {
    macosX64()
    macosArm64()
    linuxX64()
    mingwX64()

    targets.withType<KotlinNativeTarget> {
        binaries {
            executable {
                baseName = "ktools"
                entryPoint = "dev.sriniketh.main"
                runTaskProvider?.configure {
                    val args = providers.gradleProperty("runArgs")
                    argumentProviders.add(CommandLineArgumentProvider {
                        args.orNull?.split(' ') ?: emptyList()
                    })
                }
            }
        }
    }

    sourceSets {

        commonMain.dependencies {
            implementation(libs.kotlinx.datetime)
            implementation(libs.okio.core)
            implementation(libs.kotlinx.serialization)
            implementation(libs.ktor.client)
        }
        commonTest.dependencies {
            implementation(libs.okio.fakefilesystem)
        }
        nativeMain.dependencies {
            implementation(libs.clikt)
        }
    }
}

fun getVersionNameFromGitTags(): String {
    return providers.exec {
        commandLine("git", "describe", "--tags")
    }.standardOutput.asText.get().trim()
}

// dokka plugin config
dokka {
    dokkaPublications.html {
        outputDirectory.set(file("${rootDir}/docs/dokka/"))
    }
    dokkaSourceSets.configureEach {
        displayName.set(name)
        sourceLink {
            localDirectory.set(file("src/$name/kotlin"))
            remoteUrl("https://github.com/sriniketh/ktools/tree/main/src/$name/kotlin")
            remoteLineSuffix.set("#L")
        }
        suppressedFiles.from(file("src/$name/kotlin/dev/sriniketh/Main.kt"))
    }
}

// about libraries plugin config
aboutLibraries {
    export {
        outputFile = file("src/nativeMain/resources/librariesandlicenses.json")
        prettyPrint = true
    }
}

// build config plugin config
buildConfig {
    documentation.set("Generated by BuildConfig plugin")
    buildConfigField("VERSION", version.toString())
    buildConfigField(
        name = "ABOUT_LIBRARIES_JSON",
        value = provider { file("src/nativeMain/resources/librariesandlicenses.json").readText() }
    )
}

// Keep the checked-in aboutlibraries export current: every generated BuildConfig embeds
// `librariesandlicenses.json` as a string (see `ABOUT_LIBRARIES_JSON` above), read lazily at task
// execution time. Without this, the JSON only gets refreshed when someone remembers to run
// `exportLibraryDefinitions` by hand after a dependency bump, so the shipped `--about` output
// silently drifts from the real version catalog. `exportLibraryDefinitions` only reads metadata
// (POMs) already fetched during normal dependency resolution, so it's safe and network-free to run
// on every build - wiring it as a task dependency (rather than a separate CI freshness check) means
// `./gradlew build` regenerates the JSON automatically and it can never go stale again.
tasks.matching {
    it.name.startsWith("generate") && it.name.endsWith("BuildConfigClasses")
}.configureEach {
    dependsOn("exportLibraryDefinitions")
}

// exportLibraryDefinitions writes into src/nativeMain/resources, which every *ProcessResources
// task for a native/metadata target also reads from when packaging that source set's resources.
// Now that exportLibraryDefinitions runs as part of a normal build (wired in above), Gradle's task
// validation flags that overlap as an undeclared implicit dependency unless we tell it those tasks
// must run after the export - otherwise output could be produced in the wrong order.
tasks.matching { it.name.endsWith("ProcessResources") }.configureEach {
    mustRunAfter("exportLibraryDefinitions")
}

// detekt plugin config
detekt {
    buildUponDefaultConfig = true
    config.setFrom(files("$rootDir/detekt.yml"))
}

tasks.withType<Detekt>().configureEach {
    exclude("**/build/**", "**/BuildConfig.kt")
    reports {
        html.required.set(true)
        xml.required.set(false)
        txt.required.set(false)
        sarif.required.set(false)
        md.required.set(false)
    }
}

// In this KMP project the base `detekt` lifecycle task has no sources of its own; the actual
// analysis happens in target-specific tasks (e.g. `detektMetadataCommonMain`, `detektMacosArm64Main`).
// Those aren't wired into `check` by default, so `./gradlew build` never actually gated on them.
// Wire every source-bearing detekt task into `check` so `build`/CI enforces them.
tasks.named("check") {
    dependsOn(
        tasks.matching {
            it.name.startsWith("detekt") &&
                !it.name.startsWith("detektBaseline") &&
                it.name != "detektGenerateConfig" &&
                it.name != "detekt"
        }
    )
}

// gradle versions plugin config
tasks.named<DependencyUpdatesTask>("dependencyUpdates") {
    checkForGradleUpdate = true
    outputFormatter = "html"
    outputDir = "build/dependencyUpdates"
    reportfileName = "report"

    rejectVersionIf {
        candidate.version.isNonStable()
    }
}

fun String.isNonStable(): Boolean {
    val stableKeyword = listOf("RELEASE", "FINAL", "GA").any { uppercase().contains(it) }
    val regex = "^[0-9,.v-]+(-r)?$".toRegex()
    val isStable = stableKeyword || regex.matches(this)
    return isStable.not()
}
