site_name: ktools
repo_url: https://github.com/sriniketh/ktools
repo_name: ktools
copyright: 'Copyright &copy; 2024 Sriniketh Ramachandran'
theme:
  name: material
  features:
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: 'deep purple'
      accent: 'white'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: 'deep purple'
      accent: 'white'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Overview': index.md
  - 'Commands': commands.md
  - 'Docs': dokka/ktools/dev.sriniketh/index.html

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sriniketh
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/charpointer
    - icon: fontawesome/regular/circle-user
      link: https://sriniketh.dev
